import { BusinessProfile, Customer, Transaction, ManualEntryAudit, SurveySampleBreakdown, StaffAccount } from '../types';

export const initialStaffAccounts: StaffAccount[] = [
  {
    id: 'ACC-CSH-01',
    name: "Sarah Ndung'u",
    role: 'CASHIER',
    email: 'sarah.n@zawadimart.co.ke',
    title: 'Senior POS Cashier (Till 1)',
    badgeId: 'CSH-104',
    assignedTill: '842109',
    branch: 'Westlands Commercial Hub',
    permissions: ['POS Terminal Checkout', 'STK Push Dispatch', 'Instant Code Verification', 'Shift Drawer Reconciliation'],
    status: 'ON_DUTY',
    avatarInitials: 'SN',
  },
  {
    id: 'ACC-CSH-02',
    name: 'Peter Kiprop',
    role: 'CASHIER',
    email: 'peter.k@zawadimart.co.ke',
    title: 'Counter Cashier (Till 2)',
    badgeId: 'CSH-105',
    assignedTill: '842109',
    branch: 'Westlands Commercial Hub',
    permissions: ['POS Terminal Checkout', 'STK Push Dispatch', 'Instant Code Verification'],
    status: 'ACTIVE',
    avatarInitials: 'PK',
  },
  {
    id: 'ACC-MGR-01',
    name: 'James Kamau',
    role: 'MANAGER',
    email: 'james.kamau@zawadimart.co.ke',
    title: 'Branch General Manager',
    badgeId: 'MGR-001',
    assignedTill: 'Store Super Admin (Till 842109 & Paybill 522522)',
    branch: 'Westlands Commercial Hub',
    permissions: ['Full Store Administration', 'Real-time Financial Analytics', 'Exercise Notebook Audit Reconciliation', 'Daraja API Key Management', 'Till & Business Settings', 'Ledger Export'],
    status: 'ACTIVE',
    avatarInitials: 'JK',
  },
  {
    id: 'ACC-RES-01',
    name: 'Dr. Margaret Otieno',
    role: 'RESEARCHER',
    email: 'm.otieno@uonbi.ac.ke',
    title: 'Principal FinTech Researcher (PhD)',
    badgeId: 'RES-882',
    assignedTill: 'Academic Sandbox & Audit Data',
    branch: 'Faculty of Computing & Information Systems',
    permissions: ['TAM Simulator Model Adjustments', 'Empirical Audit Leakage Analysis', 'Thesis Chapters 1-5 Access', '120 SME Survey Data', 'Research Dataset Export'],
    status: 'ACTIVE',
    avatarInitials: 'MO',
  },
];

export const initialBusiness: BusinessProfile = {
  id: 'BIZ-254-001',
  name: 'Zawadi Mart & Supermarket',
  category: 'Retail & Grocery',
  tillNumber: '842109',
  paybillNumber: '522522',
  accountRef: 'ZAW-WESTLANDS',
  currency: 'KES',
  branch: 'Westlands Commercial Hub, Nairobi',
  phone: '+254 722 000 111',
  email: 'accounts@zawadimart.co.ke',
  address: 'Ring Road, Westlands, Nairobi, Kenya',
  dailyTarget: 150000,
};

export const initialTransactions: Transaction[] = [
  {
    id: 'TXN-901',
    code: 'SB45HG98LK',
    customerPhone: '+254 723 458 912',
    customerName: 'Wanjiku Mwangi',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 3450,
    fee: 0,
    paymentMethod: 'MPESA_TILL',
    status: 'COMPLETED',
    timestamp: new Date(Date.now() - 1000 * 60 * 14).toISOString(), // 14 mins ago
    reference: 'POS-REC-10492',
    tillNumber: '842109',
    verifiedBy: 'Cashier (Till 1)',
    verifiedAt: new Date(Date.now() - 1000 * 60 * 13).toISOString(),
    smsReceiptText: 'SB45HG98LK Confirmed. Ksh3,450.00 paid to Zawadi Mart Till 842109. Balance: Ksh18,240.00. Transaction cost, Ksh0.00.',
    notes: 'Groceries & Household Goods',
  },
  {
    id: 'TXN-902',
    code: 'RD72PQ11XM',
    customerPhone: '+254 711 902 341',
    customerName: 'Brian Ochieng',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 1850,
    fee: 0,
    paymentMethod: 'MPESA_EXPRESS',
    status: 'COMPLETED',
    timestamp: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    reference: 'POS-REC-10491',
    accountRef: 'ZAW-WESTLANDS',
    verifiedBy: 'Auto STK Callback',
    verifiedAt: new Date(Date.now() - 1000 * 60 * 38).toISOString(),
    smsReceiptText: 'RD72PQ11XM Confirmed. Ksh1,850.00 sent to Zawadi Mart for account ZAW-WESTLANDS. Balance: Ksh7,120.00.',
    notes: 'Bakery & Dairy items',
  },
  {
    id: 'TXN-903',
    code: 'TK90WM42XZ',
    customerPhone: '+254 734 812 559',
    customerName: 'Faith Cherono',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 5200,
    fee: 0,
    paymentMethod: 'MPESA_PAYBILL',
    status: 'COMPLETED',
    timestamp: new Date(Date.now() - 1000 * 60 * 65).toISOString(),
    reference: 'POS-REC-10490',
    paybillNumber: '522522',
    accountRef: 'INV-4029',
    verifiedBy: 'Cashier (Till 2)',
    verifiedAt: new Date(Date.now() - 1000 * 60 * 64).toISOString(),
    smsReceiptText: 'TK90WM42XZ Confirmed. Ksh5,200.00 sent to Zawadi Mart 522522 account INV-4029.',
    notes: 'Electronics Accessory Pack',
  },
  {
    id: 'TXN-904',
    code: 'AM61VV78PL',
    customerPhone: '+254 750 234 890',
    customerName: 'David Kimani',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 920,
    fee: 0,
    paymentMethod: 'AIRTEL_MONEY',
    status: 'COMPLETED',
    timestamp: new Date(Date.now() - 1000 * 60 * 115).toISOString(),
    reference: 'POS-REC-10489',
    tillNumber: '842109',
    verifiedBy: 'Cashier (Till 1)',
    verifiedAt: new Date(Date.now() - 1000 * 60 * 114).toISOString(),
    smsReceiptText: 'Airtel Money Ref AM61VV78PL. Paid KES 920.00 to Zawadi Mart Till 842109.',
    notes: 'Beverages & Snacks',
  },
  {
    id: 'TXN-905',
    code: 'QR88MK39AA',
    customerPhone: '+254 728 554 120',
    customerName: 'Amina Hassan',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 14200,
    fee: 0,
    paymentMethod: 'QR_PAY',
    status: 'COMPLETED',
    timestamp: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    reference: 'POS-REC-10488',
    tillNumber: '842109',
    verifiedBy: 'Auto QR Instant Pay',
    verifiedAt: new Date(Date.now() - 1000 * 60 * 140).toISOString(),
    smsReceiptText: 'QR88MK39AA Confirmed. Ksh14,200.00 paid via Dynamic QR to Zawadi Mart.',
    notes: 'Bulk Wholesale Order',
  },
  {
    id: 'TXN-906',
    code: 'MP55ZZ12QW',
    customerPhone: '+254 701 445 789',
    customerName: 'Hillary Makedi',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 2750,
    fee: 0,
    paymentMethod: 'MPESA_TILL',
    status: 'COMPLETED',
    timestamp: new Date(Date.now() - 1000 * 60 * 185).toISOString(),
    reference: 'POS-REC-10487',
    tillNumber: '842109',
    verifiedBy: 'Cashier (Till 1)',
    verifiedAt: new Date(Date.now() - 1000 * 60 * 184).toISOString(),
    smsReceiptText: 'MP55ZZ12QW Confirmed. Ksh2,750.00 paid to Zawadi Mart Till 842109.',
    notes: 'Fresh Produce & Pantry',
  },
  {
    id: 'TXN-907',
    code: 'FL44NN09XX',
    customerPhone: '+254 712 999 888',
    customerName: 'Dennis Mutua',
    businessId: 'BIZ-254-001',
    businessName: 'Zawadi Mart & Supermarket',
    amount: 680,
    fee: 0,
    paymentMethod: 'MPESA_EXPRESS',
    status: 'FAILED',
    timestamp: new Date(Date.now() - 1000 * 60 * 220).toISOString(),
    reference: 'POS-REC-10486',
    accountRef: 'ZAW-WESTLANDS',
    smsReceiptText: 'Failed: The initiator information is invalid or customer cancelled prompt.',
    notes: 'Customer cancelled PIN prompt',
  },
];

export const initialCustomers: Customer[] = [
  {
    id: 'CUST-01',
    name: 'Wanjiku Mwangi',
    phone: '+254 723 458 912',
    email: 'wanjiku.m@gmail.com',
    totalSpent: 42300,
    transactionCount: 14,
    loyaltyPoints: 423,
    lastVisit: 'Today, 10:45 AM',
    tier: 'GOLD',
    walletBalance: 18450,
    memberSince: 'Jan 2024',
    avatarInitials: 'WM',
  },
  {
    id: 'CUST-02',
    name: 'Brian Ochieng',
    phone: '+254 711 902 341',
    email: 'bochieng@yahoo.com',
    totalSpent: 18900,
    transactionCount: 8,
    loyaltyPoints: 189,
    lastVisit: 'Today, 10:20 AM',
    tier: 'SILVER',
    walletBalance: 7120,
    memberSince: 'Mar 2024',
    avatarInitials: 'BO',
  },
  {
    id: 'CUST-03',
    name: 'Faith Cherono',
    phone: '+254 734 812 559',
    email: 'faith.cherono@outlook.com',
    totalSpent: 65400,
    transactionCount: 21,
    loyaltyPoints: 654,
    lastVisit: 'Today, 09:50 AM',
    tier: 'PLATINUM',
    walletBalance: 34900,
    memberSince: 'Nov 2023',
    avatarInitials: 'FC',
  },
  {
    id: 'CUST-04',
    name: 'David Kimani',
    phone: '+254 750 234 890',
    email: 'dkimani@biz.co.ke',
    totalSpent: 12500,
    transactionCount: 5,
    loyaltyPoints: 125,
    lastVisit: 'Today, 09:00 AM',
    tier: 'BRONZE',
    walletBalance: 4200,
    memberSince: 'Jun 2024',
    avatarInitials: 'DK',
  },
  {
    id: 'CUST-05',
    name: 'Amina Hassan',
    phone: '+254 728 554 120',
    email: 'amina.h@safari.com',
    totalSpent: 128000,
    transactionCount: 34,
    loyaltyPoints: 1280,
    lastVisit: 'Today, 08:35 AM',
    tier: 'PLATINUM',
    walletBalance: 92300,
    memberSince: 'Aug 2023',
    avatarInitials: 'AH',
  },
  {
    id: 'CUST-06',
    name: 'Hillary Makedi',
    phone: '+254 701 445 789',
    email: 'hillary.makedi@gmail.com',
    totalSpent: 28400,
    transactionCount: 11,
    loyaltyPoints: 284,
    lastVisit: 'Today, 07:55 AM',
    tier: 'GOLD',
    walletBalance: 22800,
    memberSince: 'Feb 2024',
    avatarInitials: 'HM',
  },
];

// Reconciling Digital Ledger with the traditional paper exercise notebook (Chapter 4.1 issue)
export const initialAudits: ManualEntryAudit[] = [
  {
    id: 'AUD-01',
    timestamp: 'Today, 10:45 AM',
    notebookAmount: 3450,
    systemAmount: 3450,
    customerName: 'Wanjiku Mwangi (SB45HG98LK)',
    discrepancyType: 'MATCH',
    description: 'Accurately captured in both systems.',
    recoveredValue: 0,
  },
  {
    id: 'AUD-02',
    timestamp: 'Today, 09:50 AM',
    notebookAmount: 2500,
    systemAmount: 5200,
    customerName: 'Faith Cherono (TK90WM42XZ)',
    discrepancyType: 'TRANSCRIPTION_ERROR',
    description: 'Cashier wrote transposed figures (KES 2,500 instead of 5,200) in notebook. System caught KES 2,700 underreporting.',
    recoveredValue: 2700,
  },
  {
    id: 'AUD-03',
    timestamp: 'Today, 08:35 AM',
    notebookAmount: 0,
    systemAmount: 14200,
    customerName: 'Amina Hassan (QR88MK39AA)',
    discrepancyType: 'NOTEBOOK_OMISSION',
    description: 'Cashier forgot to enter busy morning bulk order into counter exercise book. Automated system prevented complete unrecorded loss.',
    recoveredValue: 14200,
  },
  {
    id: 'AUD-04',
    timestamp: 'Yesterday, 04:15 PM',
    notebookAmount: 4800,
    systemAmount: 0,
    customerName: 'Attempted fraud: Customer showed fabricated SMS',
    discrepancyType: 'UNVERIFIED_SMS',
    description: 'Customer showed phone with fake SMS. Cashier had written it in notebook without checking system. System blocked receipt generation and flagged fake code.',
    recoveredValue: 4800,
  },
];

// Sample Size & Study Breakdown from Chapter 3.5
export const studyBreakdown: SurveySampleBreakdown[] = [
  {
    category: 'Business Owners',
    sampleSize: 20,
    satisfactionScore: 88,
    topBenefit: 'Increased sales volume & faster cash flow reconciliation',
    primaryChallenge: 'High service provider transaction fees (M-Pesa / Bank tariffs)',
  },
  {
    category: 'Business Managers',
    sampleSize: 15,
    satisfactionScore: 92,
    topBenefit: 'Elimination of cash-handling risks, internal theft, and notebook errors',
    primaryChallenge: 'Occasional network interruptions causing delayed customer alerts',
  },
  {
    category: 'Payment Cashiers & Employees',
    sampleSize: 25,
    satisfactionScore: 84,
    topBenefit: 'Faster queue clearance & automatic till balancing at shift end',
    primaryChallenge: 'Dealing with customers who present forged or delayed SMS receipts',
  },
  {
    category: 'Customers (Payers)',
    sampleSize: 40,
    satisfactionScore: 94,
    topBenefit: 'Convenience of cashless shopping, instant digital receipts, and speed',
    primaryChallenge: 'Fear of accidentally sending money to the wrong Till/Paybill number',
  },
];
